# This is a basic workflow to help you get started with Actions
name: API_Automation_for_Edutinker_Login

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create directory for reports
      - name: Create directory
        run: mkdir testArtifacts

      # Step 3: Setup Node.js (for Newman)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 4: Install Newman and reporters
      - name: Install Newman and reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-slackreporter

      # Step 5: Run API Tests (Collection contains all host/login info)
      - name: Run Postman Tests
        run: newman run "Admission/Admissions_401_Cases.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

      # Step 6: Upload Test Report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: testArtifacts
